### ISSUE TITLE
Edge case might throw ArgumentNullException (stopwatch.Stop where stopwatch is null)

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/MethodTimer#23]
We just found it in one of our apps (but we use MethodTimer a lot, so this must be an edge case). I will try to repro + fix.

**Comment by GeertvanHorrik** [comment]
I can't reproduce on my machine, need to check tomorrow with one of the other developers to see if their machine generates different IL.

**Comment by GeertvanHorrik** [comment]
Only happens with VS 2013 (non-roslyn). That explains why I can't reproduce.

**Comment by SimonCropp** [comment]
pushed. sorry for the delay

**Comment by GeertvanHorrik** [comment]
Np, I know you are very busy, thanks for accepting!
