### ISSUE TITLE
Not an issue, more a question

### ISSUE THREAD

**Issue by Tybielee** [Fody/MethodTimer#27]
So I have been trying to use MethodDecoratorEx.Fody to help with the logging in my application. Now currently I am unable to get the MethodDecoratorEx.Fody to play nicely with asynchronous methods and have opened an issue on this. However, what I really need is something that has both the Init, OnEntry, OnExit, OnException with the awesomeness that this package provide in the method timer. Because for some reason that I have no idea what the Method Timer works properly with asynchronous methods How I expect it too but the MethodDecoratorEx does not. (My guess is it lies in the finally block, but that's just my idea.)

Does anyone know if I can achieve something similar to a MethodDecoratorTimer mesh of a add-in? I have tried looking at the source code for things but it is really confusing to me. Maybe if someone could point me in the right direction of what I should do that would be great and I could fork either this project or the MethodDecoratorEx project and adds things into it. 

Thanks in advance!

**Comment by GeertvanHorrik** [comment]
I am not sure if I understand what you are looking for. Do you need help searching for all the possible endpoints (returns) of an async method, or....?

**Comment by Tybielee** [comment]
@GeertvanHorrik Sometimes I don't even think I know what I am asking. I think what I'm looking for is where do I look for the code that does the try-finally block. I want to try and implement the finally block in the MethodDecoratorEx stuff. I know that the finally block is used here but I dont know where in the source code to look at where that is implemented.

**Comment by SimonCropp** [comment]
This should really be raised against the methoddecorator project
