### ISSUE TITLE
Suppport Convention / Config for applying [Time]

### ISSUE THREAD

**Issue by ppittle** [Fody/MethodTimer#28]
It would be great if I could specify in the FodyWeavers.xml the types or an entire namespace I'd like the `[Time]` attributed projected on.

Is this possible?

**Comment by SimonCropp** [comment]
sure. send me a PR

**Comment by ppittle** [comment]
I've forked the repo and took a look through it.  It'll take me some time to get some specific questions together; but if you teach a man to fish I might be able to add the feature!

**Comment by SimonCropp** [comment]
@ppittle what do you need to know?

**Comment by ppittle** [comment]
Still working on it, so this is a bit pre-mature, but this is where I'm at thus far:

https://github.com/SkyKick/MethodTimer/commit/13462a208efe160baf3cdbcea7262c7a06bdfe0e

Outstanding questions:

a) Do you have an example of how to correctly wire in config? I was following a different plugin (SemVer.Stamp I think, but it's been a few days so I don't recall exactly).
b) Any input on naming?  I've been borrowing from AOP and using the name `PointCutRegex` both internally and the name of the field that will be exposed via the config file:

https://github.com/SkyKick/MethodTimer/blob/13462a208efe160baf3cdbcea7262c7a06bdfe0e/Fody/Configuration.cs#L37-L41

**Comment by SimonCropp** [comment]
PointCutRegex is technically correct. but most people consuming this are not aware of AOP terminology. perhaps `IncludeTypeRegex`  ?

**Comment by ppittle** [comment]
Cool, I'll change to `IncludeTypeRegex` next time I get a chance to work further on this.

Any input on the Config part of the question?  Do you have a guide for best practice for wiring it up?

**Comment by GeertvanHorrik** [comment]
@ppittle is this something you are still working on? If not, I think we can close it?

**Comment by ppittle** [comment]
Sorry guys, got put on to a different project and never got the chance to finish this up.
