### ISSUE TITLE
feature request: disable weaving if DEBUG isn't set

### ISSUE THREAD

**Issue by kenkyee** [Fody/MethodTimer#29]
Would be nice to be able to make sure the timing code isn't left in release builds by mistake :-)
In normal code, you'd do
#if DEBUG
  debug stuff
#endif

**Comment by SimonCropp** [comment]
i just pushed 1.16.0. if you wrap the code inside your logging interceptor with an `#if DEBUG` the it will be detected and no weaving will occur.

Can u confirm this works for you

**Comment by kenkyee** [comment]
Thanks, Simon.  That would work.
Unfortunately, I couldn't get Fody to work w/ Xamarin (it didn't know how to start the apps after I added it) so I had to do the cut/paste of the timing code everywhere instead :-(

**Comment by SimonCropp** [comment]
ok will close this one. can u raise another one with a repro for xamarin
