### ISSUE TITLE
Unable to obtain public key for StrongNameKeyPair

### ISSUE THREAD

**Issue by StevenLiSiwei** [Fody/MethodTimer#31]
I am facing a issue after I integrated methodtimer assembly with my project, the fody threw an exception saying Unable to obtain public key for StrongNameKeyPair. is there anyway I can supply the StrongNameKeyPair ?

Thanks
Steven

**Comment by GeertvanHorrik** [comment]
I don't think that's possible. But I think it's best asked in the general Fody repository, not this plugin.
