### ISSUE TITLE
silverlight async call NullReferenceException

### ISSUE THREAD

**Issue by kronic** [Fody/MethodTimer#35]
in MethodTimer.Stopwatch.Stop()
   in WcfExtensions.ProxyAutoRestartAsync`1.<FuncSafeAsync>d__11`1.MoveNext()

**Comment by GeertvanHorrik** [comment]
Can you provide a (server-side, non silverlight) repro? I think in all honesty none of us has a VS installation that supports Silverlight.

**Comment by kronic** [comment]
Silverlight version 5.1.50907.0
MethodTimer version 1.19.0
Fody version 2.1.0

**Comment by GeertvanHorrik** [comment]
I think we have to be realistic here that if this problem only affects Silverlight, this one won't be solved (unless you want to PR it).

**Comment by SimonCropp** [comment]
yeah unless u can repro this on non-silverlight it wont be fixed
