### ISSUE TITLE
Enhancement request (Timespan instead of milliseconds)

### ISSUE THREAD

**Issue by ipashchuk** [Fody/MethodTimer#36]
Hi, I'm playing around with Fody and came across MethodTimer.  It looks almost exactly what I want.

I have a process that performs operations on 1-2 million items.  There are about 8 methods that are called on each item.  I would like to time the total time it takes in each method for the whole set (i.e. aggregate the individual timings).  The problem I have is that the custom intercepter does not support enough precision (by using `long milliseconds`). Most of my individual calls will be in the sub-millisecond range, which would return 0, so even adding up timings for 2,000,000 iterations would still show 0.

```
public static class MethodTimeLogger
{
    public static void Log(MethodBase methodBase, long milliseconds)
    {
        //Do some logging here
    }
}
```
What do you think about providing an overload like so:
```
public static class MethodTimeLogger
{
    public static void Log(MethodBase methodBase, Timespan elapsed)
    {
        Debug.WriteLine("Elapsed ticks: {0}", elapsed.Ticks);
    }
}
```
This would allow more precision and flexibility.  In my case, the implementation would look something like this:
```
public static class MethodTimeLogger
{
    public static Dictionary<string, long> Counters = new Dictionary<string, long>();
    public static void Log(MethodBase methodBase, TimeSpan elapsed)
    {
        if (Counters.ContainsKey(methodBase.Name))
        {
            Counters[methodBase.Name] += elapsed.Ticks;
        }
        else
        {
            Counters[methodBase.Name] = elapsed.Ticks;
        }
    }
}
```
Thoughts?  I would be happy to implement it and create a pull request.

**Comment by GeertvanHorrik** [comment]
I think this is a good idea. We must maintain backwards compatibility though. What are your thoughts @SimonCropp ? I am happy to review this if you give the go, then it's off your plate.

**Comment by SimonCropp** [comment]
happy to take a PR for this
