### ISSUE TITLE
Convert to .NET Standard

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/MethodTimer#37]
I think it's time to leave PCL behind us and drop all crap (e.g. Silverlight, etc) ms has delivered over the years. 

Happy to PR.

**Comment by SimonCropp** [comment]
nah i can do it tomorrow

**Comment by SimonCropp** [comment]
this is on nuget. can u smoke test?

**Comment by GeertvanHorrik** [comment]
Looks good! I can reference it without having to add NoWarn="NU1701". Also took a quick look at the generated code, looks fine.

Thanks!
