### ISSUE TITLE
Issue with latest MethodTimer.Fody

### ISSUE THREAD

**Issue by GeertvanHorrik** [Fody/MethodTimer#40]
History: worked perfect until yesterday or so

Now I get this on a UWP project:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: An unhandled exception occurred:
Exception:
Could not find type 'Trace'.
StackTrace:
   at CecilExtensions.Type(List`1 types, String name) in C:\projects\methodtimer\MethodTimer.Fody\CecilExtensions.cs:line 148
   at ModuleWeaver.FindReferences() in C:\projects\methodtimer\MethodTimer.Fody\ReferenceFinder.cs:line 31
   at ModuleWeaver.Execute() in C:\projects\methodtimer\MethodTimer.Fody\ModuleWeaver.cs:line 37
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 182
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 87
Source:
MethodTimer.Fody
TargetSite:
Mono.Cecil.TypeDefinition Type(System.Collections.Generic.List`1[Mono.Cecil.TypeDefinition], System.String)	
```

**Comment by GeertvanHorrik** [comment]
I don't think Trace is available in UWP. In that case we could just ignore searching for the type (since I have my own templates anyway)?

**Comment by GeertvanHorrik** [comment]
Probably this line that we need to add an if (traceType != null)

https://github.com/Fody/MethodTimer/blob/8a036b6aab8b94507ae71c3d5359b909ef522592/MethodTimer.Fody/ReferenceFinder.cs#L35

**Comment by GeertvanHorrik** [comment]
And probably fallback to Debug.WriteLine. So we can just use something like this:

```
var traceType = refTypes.Type("Trace");
if (traceType == null)
{
    traceType = refTypes.Type("Debug");
}
```

The issue here is that if I use this package on *any* project on my system, it automatically gets loaded by Fody, so staying on a previous version is not really a (realistic) option.

**Comment by SimonCropp** [comment]
```
var traceType = refTypes.Type("Trace");
if (traceType == null)
{
    traceType = refTypes.Type("Debug");
}
```

I like it. pushed in 2.0.1

and sorry for the hassle.

**Comment by GeertvanHorrik** [comment]
I didn't even have to PR this :-)

Works like a charm, thanks for fixing this so fast! 👍
