### ISSUE TITLE
get Elapsed property in Interceptor

### ISSUE THREAD

**Issue by alextroto** [Fody/MethodTimer#43]
Hi,
There are cases where  high-resolution accuracy it's need it, so it would be great to get Elapsed property in Interceptor.

**Comment by SimonCropp** [comment]
how would this be done in a non breaking way?

**Comment by alextroto** [comment]
Maybe a new Interceptor ?

```
public static class MethodTimeHiResLogger
{
    public static void Log(MethodBase methodBase, TimeSpan elapsed)
    {
        //Do some logging here
    }
}
```

**Comment by SimonCropp** [comment]
That sounds reasonable. Can you submit a PR.

**Comment by alextroto** [comment]
I'm not very familiar with Fody but I'll try to understand how it's working.
In the meantime, if someone can submit a PR, it would be great.

**Comment by GeertvanHorrik** [comment]
Instead of adding a different class, why not add this (optional!) method:

```
    public static void Log(MethodBase methodBase, TimeSpan duration, string message)
    {
        //Do some logging here
    }
```

The weaver can auto-detect whether it's available or not.

**Comment by SimonCropp** [comment]
@GeertvanHorrik happy with that

**Comment by GeertvanHorrik** [comment]
Cool, I will try to find time beginning next week to implement his.
