### ISSUE TITLE
Local functions

### ISSUE THREAD

**Issue by arteny** [Fody/MethodTimer#517]
C# local functions looks like not supported? There is no logging found for it.

**Comment by ltrzesniewski** [comment]
I wrote a couple unit tests which show that local methods should already be supported: 0029a8a685486b27703d89c48710557bc892677a

Compiler-generated *types* are ignored, but compiler-generated *methods* in user-written types are still included.

**Comment by arteny** [comment]
@ltrzesniewski hmm, can't understand why it is not working for me. is it allowed when method itself has [Time] attribute and it's local function also has [Time] attribute?

**Comment by ltrzesniewski** [comment]
It should be supported, yes: a local method is a separate method in the IL, so you can still put `[Time]` on it and it will be taken into account like for any other (as long as it is not in a compiler-generated type).

Maybe try to provide a simple repro and I'll reopen this issue.
