### ISSUE TITLE
Time is not calculated correctly with Async Methods

### ISSUE THREAD

**Issue by Jimmy-Ahmed** [Fody/MethodTimer#550]
Hi,

When having the Time attribute on Async Method, the stopWatch did not stop after the method finished the execution but after its caller's execution

```
[Time]
public async Task PublicAsyncMethod()
{
    await Task.Delay(1000).ConfigureAwait(false);
}

public static void Log(MethodBase methodBase, long milliseconds, string message)
{
     // Do logging
}

[TestMethod]
public async Task MeasurePerformance_Tests()
{
    await PublicAsyncMethod().ConfigureAwait(false);
   System.Threading.Thread.Sleep(90000);
}
```

Put a breakpoint inside Log method, you will notice that the breakpoint did NOT hit after PublicAsyncMethod but after MeasurePerformance_Tests execution. so the execution time instead of being 1000ms, it will be 91000ms

**Comment by GeertvanHorrik** [comment]
That's interesting because all code for this should be generated in the state machine of the async method (in this case PublicAsyncMethod).
