### ISSUE TITLE
TimeAttribute for class and TimeIgnoreAttribute

### ISSUE THREAD

**Issue by minhhungit** [Fody/MethodTimer#56]
Hello team, sometime I need to check time for all methods of a specific class. I don't know if we supported something like that before
If we did not, can we support it.
Thank you!

**Comment by SimonCropp** [comment]
yes `TimeAttribute` can be added at the class level. not sure what you mean by `TimeIgnoreAttribute`?

BTW To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by minhhungit** [comment]
@SimonCropp  Thank for you quick reply

>TimeIgnoreAttribute
This will ignore methods that we don't want to track time (in case TimeAttribute is placed in top of class )

**Comment by SimonCropp** [comment]
in that case TimeIgnoreAttribute is not currently supported

**Comment by minhhungit** [comment]
@SimonCropp thank you for your information, hope we will support it soon 👍

**Comment by SimonCropp** [comment]
I am happy to accept PR once you become a patron
