### ISSUE TITLE
Add support for calling local log method 

### ISSUE THREAD

**Issue by AnderssonPeter** [Fody/MethodTimer#64]
If you add support for calling a local instance method or just using a local [ILogger](https://github.com/aspnet/Extensions/blob/master/src/Logging/Logging.Abstractions/src/ILogger.cs) variable.

This would make Frody.MethodTimer much more IOC friendly and a blizz to use with .net core!

Then one could write
```c#
[Time]
class Class1
{
    ILogger<Class1> logger;
    public Class1(ILogger<Class1> logger)
    {
        this.logger = logger;
    }

    public void Test()
    {
        Thread.Sleep(1000);
    }
}
```

Or if using `ILogger` is no option

```c#
[Time]
class Class1
{
    ILogger<Class1> logger;
    public Class1(ILogger<Class1> logger)
    {
        this.logger = logger;
    }

    public void Log(MethodBase methodBase, long milliseconds, string message)
    {
        logger.LogTrace("logic here");
    }

    public void Test()
    {
        Thread.Sleep(1000);
    }
}
```

**Comment by GeertvanHorrik** [comment]
I know it's not 100% pure dependency injection, but you have access to the type in your MethodTimer. In that case, you could retrieve the right logger from the IoC container yourself?

We *could* detect the `ILogger` during compilation, but will it be a field, or a property, or should we just check for a type and assume that's the one to use?

**Comment by AnderssonPeter** [comment]
@GeertvanHorrik well i would just check for a field named `logger` or `_logger` and then check its type (or that it has a method that has the same parameters).

But I'm no expert.

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
